services:
  database:
    container_name: "Database"
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
  
  api:
    container_name: "store-simulation-api"
    build:
      context: ./
    depends_on:
      - database
    ports:
      - "3000:3000"
    command: "npm start"
    # volumes:
    #   - ./node_modules
    networks:
      - app-network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=Database


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: